env:
  global:
  # Docker Repository
  - REPO=fjudith/draw.io
  # Compute docker tag
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - ALPINE_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "alpine"; else echo $TRAVIS_BRANCH-alpine ; fi`
  
sudo: required
services:
  - docker

before_install:
  # Get draw.io current latest version
  - wget https://raw.githubusercontent.com/jgraph/drawio/master/VERSION
  - export VERSION=`cat VERSION`
   # Compute docker tag again if this branch is the latest
  - export TAG=`if [ "$TRAVIS_BRANCH" == "v${VERSION}" ]; then echo "latest"; else echo $TAG ; fi`
  - export ALPINE_TAG=`if [ "$TRAVIS_BRANCH" == "v${VERSION}" ]; then echo "alpine"; else echo $ALPINE_TAG ; fi` 

jobs:
  include:
  - stage: Debian build
    env:
      - BASE_IMAGE=debian
      - HTTP_PORT=32733
      - HTTPS_PORT=32734
    script: 
      - docker build -f ${BASE_IMAGE}/Dockerfile -t ${REPO}:${VERSION} ${BASE_IMAGE}/
      - docker run --name 'drawio' -d -p ${HTTP_PORT}:8080 -p ${HTTPS_PORT}:8443 ${REPO}:${VERSION}
      - sleep 10
      - docker logs drawio
      - docker exec drawio /bin/bash -c "curl -i http://localhost:8080"
  - stage: Alpine build
    env:
      - BASE_IMAGE=alpine
      - HTTP_PORT=32735
      - HTTPS_PORT=32736
    script: 
      - docker build -f ${BASE_IMAGE}/Dockerfile -t ${REPO}:${VERSION}-${BASE_IMAGE} ${BASE_IMAGE}/
      - docker run --name "drawio-${BASE_IMAGE}" -d -p ${HTTP_PORT}:8080 -p ${HTTPS_PORT}:8443 ${REPO}:${VERSION}-${BASE_IMAGE}
      - sleep 10
      - docker logs drawio-${BASE_IMAGE}
      - docker exec drawio-${BASE_IMAGE} /bin/bash -c "curl -i http://localhost:8080"

after_success:
  - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
  - docker tag ${REPO}:${VERSION} ${REPO}:$TAG
  - docker tag ${REPO}:${VERSION}-alpine ${REPO}:$ALPINE_TAG
  - docker push ${REPO}:${TAG}
  - docker push ${REPO}:${ALPINE_TAG}
  - docker push ${REPO}:${VERSION}
  - docker push ${REPO}:${VERSION}-alpine
  # - curl -X POST https://hooks.microbadger.com/images/jgraph/drawio/L1HSeb1zjYXdXe4RIVlHXSkT6Ng=
