apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drawio
  namespace: drawio
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: draw.io
    spec:
      containers:
      - image: docker.io/fjudith/draw.io:10.7.0-alpine
        imagePullPolicy: IfNotPresent
        name: drawio
        ports:
        - containerPort: 8080
---