---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawio
  namespace: drawio
  labels:
    app: draw.io
    version: v15.7.3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: draw.io
  template:
    metadata:
      labels:
        app: draw.io
    spec:
      containers:
        - image: harbor.testruction.io/library/draw.io:15.7.3-alpine
          imagePullPolicy: IfNotPresent
          name: drawio
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          ports:
            - containerPort: 8080
---
